# Generated by Django 3.0.8 on 2020-11-19 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('os', models.TextField(default='No')),
                ('browser', models.TextField(default='No')),
                ('device', models.TextField(default='No')),
                ('mobile', models.BooleanField(default=False)),
                ('tablet', models.BooleanField(default=False)),
                ('touch_capable', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('bot', models.BooleanField(default=False)),
            ],
        ),
    ]
